version: '3.8'

services:
  # Redis for real clustering coordination
  redis:
    image: redis:7-alpine
    container_name: hypha-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - hypha-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # Deno WebSocket Server Instance 1
  hypha-server-1:
    image: hypha-cluster
    container_name: hypha-server-1
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_PORT=8080
      - SERVER_ID=hypha-server-1
      - CLUSTERED=true
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hypha-cluster
    restart: unless-stopped

  # Deno WebSocket Server Instance 2
  hypha-server-2:
    image: hypha-cluster
    container_name: hypha-server-2
    ports:
      - "8081:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_PORT=8080
      - SERVER_ID=hypha-server-2
      - CLUSTERED=true
    depends_on:
      redis:
        condition: service_healthy
      hypha-server-1:
        condition: service_started
    networks:
      - hypha-cluster
    restart: unless-stopped

  # Deno WebSocket Server Instance 3
  hypha-server-3:
    image: hypha-cluster
    container_name: hypha-server-3
    ports:
      - "8082:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_PORT=8080
      - SERVER_ID=hypha-server-3
      - CLUSTERED=true
    depends_on:
      redis:
        condition: service_healthy
      hypha-server-2:
        condition: service_started
    networks:
      - hypha-cluster
    restart: unless-stopped

  # Load Balancer (Nginx)
  nginx:
    image: nginx:alpine
    container_name: hypha-loadbalancer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hypha-server-1
      - hypha-server-2
      - hypha-server-3
    networks:
      - hypha-cluster
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  hypha-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

 